apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-service.fullname" . }}
  labels:
    {{- include "grpc-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: grpc
      name: grpc
      appProtocol: http
    {{- if .Values.tls.enabled }}
    - port: {{ add1 .Values.service.port }}
      protocol: TCP
      targetPort: grpcs
      name: grpcs
      appProtocol: https
    {{- end }}
  selector:
    {{- include "grpc-service.selectorLabels" . | nindent 4 }}
