# {{- if .Values.persistence.enabled -}}
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata: 
#   name: {{ include "tusd.fullname" . }}-pvc
#   # labels:
#   #   app.kubernetes.io/name: {{ include "tusd.name" . }}
#   #   app.kubernetes.io/instance: {{ .Release.Name }}
# spec: 
#   volumeMode: Filesystem
#   accessModes: 
#     - ReadWriteMany
#   resources: 
#     requests: 
#       storage: {{ .Values.persistence.size }}
#   volumeName: {{ include "tusd.fullname" . }}-pv
#   {{- if .Values.persistence.storageClassName }}
#   storageClassName: {{ .Values.persistence.storageClassName }}
#   {{- else if .Values.persistence.volumeName -}}
#   volumeName: {{ .Values.persistence.volumeName }}
#   {{- end }}
# {{- end }}


# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: tusd-data-pvc
#   labels:
#     app.kubernetes.io/instance: tusd
#     app.kubernetes.io/name: tusd
# spec:
#   storageClassName: openebs-rwx
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
