{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "web-service.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ template "web-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.monitoring.serviceMonitor.additionalLabels }}
    #   {{ toYaml .Values.monitoring.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: "{{ include "web-service.fullname" . }}"
  selector:
    matchLabels:
    {{- include "web-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}